from typing import Dict, Any
from ai.rag_pipeline import rag_pipeline_instance

def understand_query(query: str) -> Dict[str, Any]:
    """
    Extract intent and preferences from a natural language query.
    (This is a placeholder for backward compatibility. 
    The new RAG pipeline handles query processing internally).
    """
    return {"intent": "search", "query": query}

def explain_recommendation(movie_id: int, evidence: Dict[str, Any], user_query: str = "") -> Dict[str, Any]:
    """
    Generate a natural language explanation for why a movie was recommended
    using Grounded LLM Explainability.
    """
    try:
        explanation = rag_pipeline_instance.explain_recommendation(movie_id, user_query, evidence)
        return {"explanation": explanation}
    except Exception as e:
        return {"explanation": f"AI explanation temporarily unavailable. Error: {e}"}

def conversational_recommend(user_query: str) -> str:
    """
    Main entry point for the AI recommendation engine.
    Takes a natural language query, performs vector search in Pinecone,
    and returns a grounded, conversational recommendation generated by Llama 3.1.
    """
    try:
        response = rag_pipeline_instance.generate_recommendation(user_query=user_query)
        return response
    except Exception as e:
        # Prevent crashing the backend with unhandled exceptions
        return f"I'm sorry, I encountered a temporary issue while fetching recommendations. Error: {e}"
